// Trust is a property of where content came from, never of what it contains.
//
// CLAUDE.md §3.1 accepted a single-origin topology — the editor at /editor
// shares an origin with every published post — on the explicit condition that
// browser-authored content can never carry script. That condition is this file.
// Without it, an `onerror` typed into a post body runs where the editor's
// session cookie lives.
//
// Two paths, because they have genuinely different problems:
//
//   * **Markdown** leaks only through raw HTML passthrough. The fix is not a
//     sanitizer at all: `html: false` makes markdown-it *escape* raw markup
//     instead of emitting it, so hostile HTML is never produced in the first
//     place. Nothing to filter is stronger than filtering well. Everything else
//     in the output is generated by markdown-it, highlight.js and KaTeX, all of
//     which we configure.
//
//   * **LaTeX** leaks through URL-bearing macros. `\href{javascript:...}` and
//     `\url{...}` emit a live anchor whatever the raw-HTML setting is, so the
//     .tex path needs URL validation on *both* trust levels. Raw HTML in a .tex
//     source is already escaped by unified-latex, so there is no trusted
//     raw-markup use case to preserve and the sanitizer is unconditional there.
//
// KaTeX output never passes through here. `renderLatex` injects it after this
// runs, and markdown's math is generated inline — deliberately, because
// filtering MathML and SVG is exactly how a sanitizer breaks every equation on
// a site. KaTeX is safe by configuration instead: `trust: false` disables
// \href, \url, \includegraphics and the \html* family.

/** Where a piece of content came from. Anything not from the repository is hostile. */
export const ENGINE = "engine";   // authored in the repository, by the owner, in git
export const BROWSER = "browser"; // authored in the editor or arriving from R2

/** The default is the *safe* one, so a caller that forgets is not thereby exposed. */
export const DEFAULT_TRUST = BROWSER;

export function isTrusted(trust) {
  return trust === ENGINE;
}

// ---------------------------------------------------------------- URL policy

const SAFE_SCHEMES = new Set(["http:", "https:", "mailto:"]);

/**
 * Is this URL safe to put in an href or src?
 *
 * Control characters are stripped first: browsers ignore tabs and newlines
 * inside a URL before resolving the scheme, so `java<TAB>script:` is
 * `javascript:` to a browser and must be to us as well.
 */
export function isSafeUrl(value) {
  const url = String(value ?? "").replace(/[\u0000-\u001F\u007F]/g, "").trim();
  if (!url) return false;
  // Fragment, query and root-relative links carry no scheme.
  if (/^[#?/]/.test(url)) return true;
  // No scheme at all means relative, which cannot escape the site.
  if (!/^[a-z][a-z0-9+.-]*:/i.test(url)) return true;
  try {
    return SAFE_SCHEMES.has(new URL(url).protocol);
  } catch {
    return false;
  }
}

/**
 * Is this image served by this site?
 *
 * Browser-authored posts may only show images the blog itself serves, which
 * after publishing means `/images/uploads/<slug>/<name>`. A remote `src` makes
 * every reader's browser call a third party — leaking their address and turning
 * a post into a tracking pixel — so it is refused rather than rendered.
 *
 * Root-relative only. Protocol-relative `//host` is remote, and so is `/\host`:
 * browsers treat a backslash as a slash in http(s) URLs, so that spelling is
 * `//host` too and must not slip past a check for a leading `//`.
 */
export function isLocalImageUrl(value) {
  const url = String(value ?? "").replace(/[\u0000-\u001F\u007F]/g, "").trim();
  return url.startsWith("/") && !url.startsWith("//") && !url.includes("\\") && isSafeUrl(url);
}

// --------------------------------------------------------------- hast filter

// Elements unified-latex legitimately emits. Anything outside this is *unwrapped*
// — its children survive, its tag does not — so a construct we failed to predict
// degrades to plain content rather than either vanishing or going live.
const ALLOWED = new Set([
  "a", "abbr", "b", "blockquote", "br", "caption", "cite", "code", "col", "colgroup",
  "dd", "del", "div", "dl", "dt", "em", "figcaption", "figure", "h1", "h2", "h3",
  "h4", "h5", "h6", "hr", "i", "img", "ins", "kbd", "li", "mark", "ol", "p", "pre",
  "q", "s", "samp", "section", "small", "span", "strong", "sub", "sup", "table",
  "tbody", "td", "tfoot", "th", "thead", "tr", "u", "ul", "var", "wbr",
]);

// Dropped with their contents: an element whose *purpose* is to execute, style
// or navigate. Unwrapping these would keep the payload as visible text.
const DROPPED = new Set([
  "script", "style", "iframe", "object", "embed", "applet",
  "base", "link", "meta", "form", "input", "button", "textarea", "select",
  "noscript", "template", "frame", "frameset",
]);

// Attributes that carry a URL, and therefore a scheme worth checking. Listed in
// both hast's camelCase and plain HTML spelling, since the tree is built by a
// library rather than parsed from markup.
const URL_ATTRIBUTES = new Set([
  "href", "src", "srcset", "srcSet", "action", "formaction", "formAction",
  "poster", "cite", "data", "longdesc", "longDesc", "background", "ping",
]);

function sanitizeProperties(properties) {
  if (!properties) return properties;
  const clean = {};
  for (const [name, value] of Object.entries(properties)) {
    // Event handlers, in any spelling hast might use.
    if (/^on/i.test(name)) continue;
    // srcdoc smuggles a whole document past a src check.
    if (/^srcdoc$/i.test(name)) continue;
    if (URL_ATTRIBUTES.has(name) && !isSafeUrl(value)) continue;
    clean[name] = value;
  }
  return clean;
}

function sanitizeNode(node, options) {
  if (!node || node.type !== "element") return [node];

  const children = Array.isArray(node.children)
    ? node.children.flatMap((child) => sanitizeNode(child, options))
    : [];
  const tag = String(node.tagName ?? "").toLowerCase();

  if (DROPPED.has(tag)) return [];
  if (tag === "img" && !options.allowRemoteImages && !isLocalImageUrl(node.properties?.src)) return [];
  if (!ALLOWED.has(tag)) return children; // unwrap: keep the words, lose the tag

  node.children = children;
  node.properties = sanitizeProperties(node.properties);
  return [node];
}

/**
 * A rehype plugin that strips event handlers and unsafe URLs from the tree.
 *
 * Structural rather than textual: it edits parsed nodes, so it cannot be fooled
 * by the encoding tricks that defeat regex-based HTML filtering.
 *
 * `allowRemoteImages` is false for browser-authored content, which may show only
 * images this site serves (see isLocalImageUrl).
 */
export function rehypeSafeHtml({ allowRemoteImages = true } = {}) {
  const options = { allowRemoteImages };
  return (tree) => {
    if (Array.isArray(tree?.children)) {
      tree.children = tree.children.flatMap((node) => sanitizeNode(node, options));
    }
    return tree;
  };
}
